import { Component, ChangeDetectionStrategy, OnInit, Output, Input } from '@angular/core';
import {  HttpClient } from '@angular/common/http';
import { Router, ActivatedRoute } from '@angular/router';
import { trigger, transition, style, animate } from '@angular/animations';


const purfumes = [{
  id: 1,
  categories: [{
    Catogery: 'Citrus',
    scents: [
      {image: 'assets/images/Citrus/CITRUSMEN-1.jpg',
      description: 'GMV 2001 by GianMarco Venturi is a Woody Aromatic fragrance for men. GMV 2001 was launched in 2001. Top notes are lime, mandarin orange, grapefruit, bergamot and litsea cubeba; middle notes are coriander, eucalyptus, ginger and geranium; base notes are musk, guaiac wood and cedar.',
      name: 'GMV 2001 GianMarco Venturi for men',
      Link: 'https://www.fragrantica.com/perfume/GianMarco-Venturi/GMV-2001-5985.html',
      for: 'Women'},
      {image: 'assets/images/Citrus/CITRUSMEN-2.jpg', description: 'Aqua Di Giò opens with a splash of fresh, Calabrian Bergamot, Neroli and Green Tangerine. Light, aquatic nuances mix with Rosemary, sweet Persimmon, and warm Indonesian Patchouli to create a fresh smelling fragrance for men.',
      name: 'Aqua Di Gio For Men by Giorgio Armani',
      Link: 'https://www.giorgioarmanibeauty-usa.com/fragrances/mens-fragrances/acqua-di-gio/acqua-di-gio-eau-de-toilette/A005.html#start=3&cgid=F3_FRAGRANCES_HIM_GA_ADG',
      For: 'Men'},
      {image: 'assets/images/Citrus/CITRUSMEN-3.jpg',
      description: 'The first level brings spicy aromas of black pepper united with pink pepper from Madagascar. The second level brings in fresh aromas with the scent of leather, Sicilian lemon, Calabrian bergamot, and sandalwood which gives it a depth.The third level introduces oriental accords with Brazilian Tonka, white musk, Haiti vetiver and sandal wood. This level also reveals aromas of ginger and velvety vanilla wrapped in amber. The fourth level brings woodsy accords of cedar wood which add to the masculine character of this fragrance.',
      name: 'Allure Homme Edition Blanche Chanel for men',
      Link: 'https://www.fragrantica.com/perfume/Chanel/Allure-Homme-Edition-Blanche-2653.html',
      For: ''
      },
      {image: 'assets/images/Citrus/CITRUSMEN-4.jpg', description: ':   Celsius by Faberlic is a fragrance for men. Celsius was launched in 2016. The nose behind this fragrance is Elise Benat. Top notes are lemon zest, lime, bergamot and grapefruit; middle notes are mint, lavender and woody notes; base notes are haitian vetiver, amber and musk.',
      name: 'Celsius Faberlic for men',
      Link: 'https://www.fragrantica.com/perfume/Faberlic/Celsius-38484.html',
      For: ''},
      {image: 'assets/images/Citrus/CITRUSUNISEX-1.jpg', description: 'It was devised as a burst of citrus touches, with orange to the fore, amidst zests and leaves, lemon, mandarin, mint and blackcurrant buds. Its complexity is revealed in a unique vapor composed of oak moss and patchouli. The nose behind this fragrance is Francoise Caron.',
      name: 'Eau De Orange Verte 1979 Hermès for women and men',
      Link: 'https://www.fragrantica.com/perfume/Herm-s/Eau-D-Orange-Verte-1979-3019.html',
      For: ''},
      {image: 'assets/images/Citrus/CITRUSUNISEX-2.jpg', description: 'Justice League Green Lantern by Marmol & Son is a Aromatic Spicy fragrance for women and men. Top notes are apple, lemon zest, bergamot and green notes; middle notes are coriander, black pepper and lavender; base notes are white amber, cedar, sandalwood and seaweed.',
      name: 'Justice League Green Lantern Marmol & Son for women and men',
      Link: 'https://www.fragrantica.com/perfume/Marmol-Son/Justice-League-Green-Lantern-46349.html',
      For: ''},
    ],
    sex: "Male",
    type: "['Citrus (Zesty or tangy notes like mandarins or limes)']",
  }, {
    Catogery: 'Citrus',
    scents: [
      {image: 'assets/images/Citrus/CITRUSWOMEN-1.jpg', description: 'No 105 Tender Rose by Stradivarius is a Floral Fruity Gourmand fragrance for women. This is a new fragrance. No 105 Tender Rose was launched in 2019. Top note is pomelo; middle note is neroli; base notes are caramel and vanilla',
      name: 'No 105 Tender Rose Stradivarius for women',
      Link: 'https://www.fragrantica.com/perfume/Stradivarius/No-105-Tender-Rose-58211.html',
      For: ''},
      {image: 'assets/images/Citrus/CITRUSWOMEN-2.jpg',description: 'White Grapefruit & May Chang by Abahna is a Citrus fragrance for women. White Grapefruit & May Chang was launched in 2011. The fragrance features white grapefruit and litsea cubeba.',
      name: 'White Grapefruit & May Chang Abahna for women',
      Link: 'https://www.fragrantica.com/perfume/Abahna/White-Grapefruit-May-Chang-16712.html',
      For: ''},
      {image: 'assets/images/Citrus/CITRUSWOMEN-3.jpg', description: 'This oriental fragrance embodies timeless sophistication, luxury and sensuality. The richness of its dark chords as well as its delicious notes make it a unique, voluptuous and daring fragrance.',
      name: 'Black Orchid by Tom Ford',
      Link: 'https://www.sephora.fr/p/black-orchid---eau-de-parfum-P55019.html',
      For: ''},
      {image: 'assets/images/Citrus/CITRUSWOMEN-4.jpg', description: 'Lemon Green Tea by Mary Kay is a Floral Green fragrance for women. Lemon Green Tea was launched in 2015. Top notes are green notes, lemon zest, pineapple and anise; middle notes are cyclamen, jasmine, green tea and osmanthus; base notes are vetiver, sandalowood, amber and musk.',
      name: 'Lemon Green Tea Mary Kay for women',
      Link: 'https://www.fragrantica.com/perfume/Mary-Kay/Lemon-Green-Tea-35620.html',
      For: ''},
      {image: 'assets/images/Citrus/CITRUSUNISEX-1.jpg', description: 'It was devised as a burst of citrus touches, with orange to the fore, amidst zests and leaves, lemon, mandarin, mint and blackcurrant buds. Its complexity is revealed in a unique vapor composed of oak moss and patchouli. The nose behind this fragrance is Francoise Caron.',
      name: 'Eau De Orange Verte 1979 Hermès for women and men',
      Link: 'https://www.fragrantica.com/perfume/Herm-s/Eau-D-Orange-Verte-1979-3019.html',
      For: ''},
      {image: 'assets/images/Citrus/CITRUSUNISEX-2.jpg', description: 'Justice League Green Lantern by Marmol & Son is a Aromatic Spicy fragrance for women and men. Top notes are apple, lemon zest, bergamot and green notes; middle notes are coriander, black pepper and lavender; base notes are white amber, cedar, sandalwood and seaweed.',
      name: 'Justice League Green Lantern Marmol & Son for women and men',
      Link: 'https://www.fragrantica.com/perfume/Marmol-Son/Justice-League-Green-Lantern-46349.html',
      For: ''},
    ],
    sex: "Female",
    type: "['Citrus (Zesty or tangy notes like mandarins or limes)']",
  }, {
    Catogery: 'Floral',
    scents: [
      {image: 'assets/images/Floral/FLORALMEN-1.jpg',
      description: 'Its special floral freshness combines orange blossom with incensy, woody and fresh notes which we also find in aromatic Fleur du Male by Jean Paul Gaultier and oriental Fahrenheit 32. Among main perfume notes in the new Fahrenheit fragrance, are iris, rose, violet, orange blossom, vetiver and vanilla.',
      name: 'Fahrenheit 32 by Christian Dior',
      Link: 'https://www.fragrantica.com/perfume/Christian-Dior/Fahrenheit-32-987.html',
      For: 'Men'},
      {image: 'assets/images/Floral/FLORALMEN-2.jpg',
      description: 'Dior Homme by Christian Dior is a Woody Floral Musk fragrance for men. Dior Homme was launched in 2011. The nose behind this fragrance is Francois Demachy. Top notes are lavender, sage and bergamot; middle notes are iris, amber and cacao; base notes are vetiver, patchouli and leather.',
      name: 'Dior Homme Christian Dior for men',
      Link: 'https://www.fragrantica.com/perfume/Christian-Dior/Dior-Homme-13015.html',
      For: 'FOR MEN'},
      {image: 'assets/images/Floral/FLORALMEN-3.jpg', description: 'Ukiyo-E by Gri Gri Parfums is a Aromatic fragrance for men. Ukiyo-E was launched in 2016. The nose behind this fragrance is Anaïs Biguine. Top notes are yuzu and genmaicha; middle notes are daphne and green tea; base notes are japanese cherry blossom and heather.',
      name: 'Ukiyo-E Gri Gri Parfums for men',
      Link: 'https://www.fragrantica.com/perfume/Gri-Gri-Parfums/Ukiyo-E-35555.html',
      For: 'For Men'},
      {image: 'assets/images/Floral/FLORALMEN-4.jpg', description: 'Rising Wave Black by Christian Riese Lassen is a Woody Floral Musk fragrance for men. Rising Wave Black was launched in 2008. Top notes are lemon, bergamot and black currant; middle notes are jasmine, lily-of-the-valley, lily, blue poppy and peach; base notes are brazilian rosewood, musk, vanilla and amber.',
      name: 'Rising Wave Black Christian Riese Lassen for men',
      Link: 'https://www.fragrantica.com/perfume/Christian-Riese-Lassen/Rising-Wave-Black-21742.html',
      For: 'For Men'},
      {image: 'assets/images/Floral/FLORALUNISEX-1.jpg', description: 'A fresh woody fragrance unisex with a fresh opening of bergamot, mandarin, juniper, lavender, peppermint and green notes. In the heart of the composition is jasmine, orchid, freesia, magnolia with a fresh hint of peach. There are cedar, amber, musk, sandal and vanilla in the base.',
      name: 'Ck Be by Calvin Klein ',
      Link: 'https://www.fragrantica.com/perfume/Calvin-Klein/CK-be-275.html',
      For: 'UNISEX'},
      {image: 'assets/images/Floral/FLORALUNISEX-2.jpg', description: 'There is also a hidden note rendered from precious civet coffee seeds. Traditionally harvested seeds with distinct aroma bring in a rather musky yet luxurious, subtly inviting scent, tempered with softly burn spice wood chips. So, dare yourself; and, come open the casket and explore the world of ‘Morah’ with your own senses.',
      name: 'Morah Pryn Parfum for women and men',
      Link: 'https://www.fragrantica.com/perfume/Pryn-Parfum/Morah-47689.html',
      For: 'UNISEX'},
    ],
    sex: 'Male',
    type: "['Floral (Smells like fresh-cut flowers - imagine rose, lily or jasmine)']",
  },{
    Catogery: 'Floral',
    scents: [
      {image: 'assets/images/Floral/FLORALWOMEN-1.jpg', description: 'The nose behind this fragrance is Pierre Negrin. The fragrance features spices, lime, amber, fig leaf, mandarin orange, musk, orchid, almond blossom, vanilla, jasmine, lemon, sandalwood and geranium',
      name: 'Ralph Hot by Ralph Lauren',
      Link: 'https://www.fragrantica.com/perfume/Ralph-Lauren/Ralph-Hot-1898.html',
      For: 'FEMALE'},
      {image: 'assets/images/Floral/FLORALWOMEN-2.jpg', description: 'The Girl by Tommy Hilfiger is announced as a lively and fresh scent that evokes mild sunny days near the seacoast. The composition opens with a wave of green notes of pear, violet leaf and fig leaves. The heart of white jasmine flowers and lily of the valley provide a silky texture to the scent. Cedar and cashmere wrap the base of the perfume up with a woody character',
      name: 'Tommy Girl by Tommy Hilfiger',
      Link: 'https://www.fragrantica.com/perfume/Tommy-Hilfiger/The-Girl-39264.html',
      For: 'FEMALE'},
      {image: 'assets/images/Floral/FLORALWOMEN-3.jpg', description: 'Eau de Cartier Concentree by Cartier is a Citrus Aromatic fragrance for women and men. Eau de Cartier Concentree was launched in 2002. The nose behind this fragrance is Christine Nagel. Top notes are coriander and yuzu; middle notes are violet leaf and lavender; base notes are cedar, patchouli and white amber.',
      name: 'Eau de Cartier by Cartier',
      Link: 'https://www.fragrantica.com/perfume/Cartier/Eau-de-Cartier-Concentree-2442.html',
      For: 'FEMALE'},
      {image: 'assets/images/Floral/FLORALWOMEN-4.jpg', description: 'Voluptuous and mystic tuberose which makes you live dangerously rules in the heart of eau de parfum Fragile. As usual, Gaultier plays with our associations. Fragile is the warning word usually printed on the outer package with delicate and breakable items, and the box of Fragile was made in that fashion. It is fun and intriguing. Intoxicating smell of tuberose in the top notes is followed by raspberry leaves and sweet orange blossoms; pink pepper and other spices compose the heart, while the warm woody notes and light musk create a dazzling lingering trace.',
      name: 'Fragile by Jean-Paul Gaultier ',
      Link: 'https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Fragile-434.html',
      For: 'FEMALE'},
      {image: 'assets/images/Floral/FLORALUNISEX-1.jpg', description: 'A fresh woody fragrance unisex with a fresh opening of bergamot, mandarin, juniper, lavender, peppermint and green notes. In the heart of the composition is jasmine, orchid, freesia, magnolia with a fresh hint of peach. There are cedar, amber, musk, sandal and vanilla in the base.',
      name: 'Ck Be by Calvin Klein ',
      Link: 'https://www.fragrantica.com/perfume/Calvin-Klein/CK-be-275.html',
      For: 'UNISEX'},
      {image: 'assets/images/Floral/FLORALUNISEX-2.jpg', description: 'There is also a hidden note rendered from precious civet coffee seeds. Traditionally harvested seeds with distinct aroma bring in a rather musky yet luxurious, subtly inviting scent, tempered with softly burn spice wood chips. So, dare yourself; and, come open the casket and explore the world of ‘Morah’ with your own senses.',
      name: 'Morah Pryn Parfum for women and men',
      Link: 'https://www.fragrantica.com/perfume/Pryn-Parfum/Morah-47689.html',
      For: 'UNISEX'},
    ],
    sex: 'Female',
    type: "['Floral (Smells like fresh-cut flowers - imagine rose, lily or jasmine)']",
  },{
    Catogery: 'Fruity',
    scents: [
      {image: 'assets/images/Fruity/FRUITYMEN-1.jpg', description: 'Polo Black by Ralph Lauren is a Woody Aromatic fragrance for men. Polo Black was launched in 2005. The nose behind this fragrance is Pierre Negrin. The fragrance features sandalwood, tonka bean, patchouli, mango, sage, tangerine, lemon and wormwood.',
      name: 'Polo Black by Ralph Lauren',
      Link: 'https://www.fragrantica.com/perfume/Ralph-Lauren/Polo-Black-1197.html',
      For: 'MEN'},
      {image: 'assets/images/Fruity/FRUITYMEN-2.jpg', description: ':   Feelin Sexy For Him by Hinode is a Woody Aromatic fragrance for men. This is a new fragrance. Top notes are bergamot, black pepper and acai berry; middle notes are tobacco leaf, green apple and bamboo; base notes are coton candy, musk, indonesian patchouli leaf, cashmere wood and leather.',
      name: 'Feelin Sexy For Him Hinode for men',
      Link: 'https://www.fragrantica.com/perfume/Hinode/Feelin-Sexy-For-Him-56356.html',
      For: 'MEN'},
      {image: 'assets/images/Fruity/FRUITYMEN-3.jpg', description: 'The elegant blend of light, fresh smooth fruits spiced with the aroma of green leaves and warm notes of musk, amber, and sycamore wood. This scent is dedicated to the modern man with charisma and self-confidence.Notes:White Lemon, Rosewood, Carambola, Tarragon, Cedar Leaves, Clary Sage, Musk, Amber, Sycamore Wood.',
      name: 'Axis Grand Prix No 98 Axis for men',
      Link: 'https://www.fragrantica.com/perfume/Axis/Axis-Grand-Prix-No-98-13203.html',
      For: 'MEN'},
      {image: 'assets/images/Fruity/FRUITYMEN-4.jpg', description: 'Deserve Blue by Estiara is a Woody Floral Musk fragrance for men. Top notes are bergamot, litchi, lotus and orange blossom; middle notes are water notes, rose and woody notes; base notes are amber and musk.',
      name: 'Deserve Blue Estiara for men',
      Link: 'https://www.fragrantica.com/perfume/Estiara/Deserve-Blue-27776.html',
      For: 'MEN'},
      {image: 'assets/images/Fruity/FRUITYUNISEX-1.jpg', description: 'My lips could still taste grapefruit and green apple from our Sauvignon Blanc, blended with his kiss. The New York skyline floated on the horizon, cast in pastel light from the sunset. The nose behind this fragrance is Kelly Jones.',
      name: 'No. 1 Notes of Sauvignon Blanc Kelly & Jones for women and men',
      Link: 'https://www.fragrantica.com/perfume/Kelly-Jones/No-1-Notes-of-Sauvignon-Blanc-35905.html',
      For: 'UNISEX'},
      {image: 'assets/images/Fruity/FRUITYUNISEX-2.jpg', description: 'Blue Dream opens with the strains signature sweet blueberry aroma with just a hint of skunk and evolves into an earthy pepper scent with a lingering sweetness making the fragrance just as smooth and balanced as its flowering inspiration. To achieve a true to life interpretation of Blue Dream, the formula combines both synthetic fragrance oils with natural terpenes found in cannabis, including Alpha & Beta Pinene, Linalool, and Caryophyllene.',
      name: 'Blue Dream Xyrena for women and men',
      Link: 'https://www.fragrantica.com/perfume/Xyrena/Blue-Dream-43463.html',
      For: 'UNISEX'},
    ],
    sex: 'Male',
    type: "['Fruity (Sweet, edible and tropical like peach, pear and apple)']",
  },{
    Catogery: 'Fruity',
    scents: [
      {image: 'assets/images/Fruity/FRUITYWOMEN-1.jpg', description: 'The composition opens with softly fresh mandarin, bergamot, litchi and peach. The heart is thin and balmy, with the notes of jasmine, lily of the valley and white lily which graciously intertwine with the fruity touch of plum. The woodsy-powdery base is created of vetiver root, amber, musk and vanilla. The nose behind this fragrance is Christine Nagel.',
      name: 'The One by Dolce & Gabbana',
      Link: 'https://www.fragrantica.com/perfume/Dolce-Gabbana/The-One-698.html',
      For: 'FEMALE'},
      {image: 'assets/images/Fruity/FRUITYWOMEN-2.jpg', description: ':   Sweet and gourmand notes of pop corns in the heart, so unusual, make this perfume appealing to youngstersThe top notes are wild strawberry leaves and green tangerine. The heart features caramel pop corns surrounded by violets, wild strawberry, so strong and seductive and pink jasmine. The base is created of fresh patchouli leaves and crystalline musk.',
      name: 'Miss Dior Cherie by Dior',
      Link: 'https://www.fragrantica.com/perfume/Christian-Dior/Miss-Dior-Cherie-213.html',
      For: 'FEMALE'},
      {image: 'assets/images/Fruity/FRUITYWOMEN-3.jpg', description: 'The fragrance is fresh and sweet with a touch of spice. The opening of apple, cyclamen, melon, papaya, peach and Aglaia Odorata are transparent and succulently fruity. The heart is sweet and warm, composed of jasmine, lily and orris. Base notes sandalwood, amber, vanilla, cedar and resin. The nose behind this fragrance is Ursula Wandel.',
      name: 'Hugo for Women by Hugo Boss',
      Link: 'https://www.fragrantica.com/perfume/Hugo-Boss/Hugo-Woman-380.html',
      For: 'FEMALE'},
      {image: 'assets/images/Fruity/FRUITYWOMEN-4.jpg', description: 'Beyoncé Heat The Mrs. Carter Show World Tour Limited Edition by Beyonce is a Floral Fruity fragrance for women.  Top notes are pink pepper, mangosteen and acai berry; middle notes are orchid, violet and jasmine; base notes are australian sandalwood, vetiver and madagascar vanilla.',
      name: 'Beyoncé Heat The Mrs. Carter Show World Tour Limited Edition Beyonce for women',
      Link: 'https://www.fragrantica.com/perfume/Beyonce/Beyonc-Heat-The-Mrs-Carter-Show-World-Tour-Limited-Edition-18583.html',
      For: 'FEMALE'},
      {image: 'assets/images/Fruity/FRUITYUNISEX-1.jpg', description: 'My lips could still taste grapefruit and green apple from our Sauvignon Blanc, blended with his kiss. The New York skyline floated on the horizon, cast in pastel light from the sunset. The nose behind this fragrance is Kelly Jones.',
      name: 'No. 1 Notes of Sauvignon Blanc Kelly & Jones for women and men',
      Link: 'https://www.fragrantica.com/perfume/Kelly-Jones/No-1-Notes-of-Sauvignon-Blanc-35905.html',
      For: 'UNISEX'},
      {image: 'assets/images/Fruity/FRUITYUNISEX-2.jpg', description: 'Blue Dream opens with the strains signature sweet blueberry aroma with just a hint of skunk and evolves into an earthy pepper scent with a lingering sweetness making the fragrance just as smooth and balanced as its flowering inspiration. To achieve a true to life interpretation of Blue Dream, the formula combines both synthetic fragrance oils with natural terpenes found in cannabis, including Alpha & Beta Pinene, Linalool, and Caryophyllene.',
      name: 'Blue Dream Xyrena for women and men',
      Link: 'https://www.fragrantica.com/perfume/Xyrena/Blue-Dream-43463.html',
      For: 'UNISEX'},
    ],
    sex: 'Female',
    type: "['Fruity (Sweet, edible and tropical like peach, pear and apple)']",
  },{
    Catogery: 'Green',
    scents: [
      {image: 'assets/images/Green/GREENMEN-1.jpg', description: 'Eros was created by Aurelien Guichard of Givaudan and it was announced as fresh, woody and slightly oriental. The fragrance includes mint oil combined with green apple and Italian lemon. Warmth is provided by tonka mixed with Venezuelan ambroxan and geranium flowers giving a fougere twist to the fragrance this way.',
      name: 'Eros Versace for men',
      Link: 'https://www.fragrantica.com/perfume/Versace/Eros-16657.html',
      For: 'MEN'},
      {image: 'assets/images/Green/GREENMEN-2.jpg', description: 'CK Free is a modern, masculine fragrance for men, which arrives on the market in August 2009. Top notes incorporate absynth, jackfruit, star annis and juniper berries. A heart adds a union of suede, coffee, tobacco leaf and buchu (Agathosma betulina), while a base offers oak, patchouli, cedar and ironwood. CK Free was created by Rodrigo Flores-Roux and Ellen Molner.',
      name: 'CK Free Calvin Klein for men',
      Link: 'https://www.fragrantica.com/perfume/Calvin-Klein/CK-Free-6281.html',
      For: 'MEN'},
      {image: 'assets/images/Green/GREENMEN-3.jpg', description: 'Truth For Men by Calvin Klein is a Aromatic Fougere fragrance for men. Truth For Men was launched in 2002. Truth For Men was created by Givaudan and Michel Almairac. Top notes are green leaves, cardamom and basil; middle notes are resins and fern; base notes are red cedar, patchouli and exotic woods.',
      name: 'Truth For Men Calvin Klein for men',
      Link: 'https://www.fragrantica.com/perfume/Calvin-Klein/Truth-For-Men-268.html',
      For: 'MEN'},
      {image: 'assets/images/Green/GREENMEN-4.jpg', description: 'Boss Bottled United by Hugo Boss is a Woody Aromatic fragrance for men. Boss Bottled United was launched in 2018. Top notes are buchu or agathosma, blood orange and ozonic notes; middle notes are mint, orris, spicy mint, apple, lily-of-the-valley and melon; base notes are vetiver, patchouli, cashmeran, amberwood, coumarin and white musk.',
      name: 'Boss Bottled United Hugo Boss for men',
      Link: 'https://www.fragrantica.com/perfume/Hugo-Boss/Boss-Bottled-United-50109.html',
      For: 'MEN'},
      {image: 'assets/images/Green/GREENUNISEX-1.jpg', description: 'The nose behind this fragrance is Jean-Claude Ellena. Top notes are coriander, orange blossom, mandarin orange, bergamot, cardamom and lemon; middle notes are jasmine, lily-of-the-valley and bulgarian rose; base notes are sandalwood, amber, musk, green tea, precious woods and cedar.',
      name: 'Eau Parfumee au The Vert Bvlgari for women and men',
      Link: 'https://www.fragrantica.com/perfume/Bvlgari/Eau-Parfumee-au-The-Vert-144.html',
      For: 'UNISEX'},
      {image: 'assets/images/Green/GREENUNISEX-2.jpg', description: 'The stirring spice of saffron and coriander opens the scent, infiltrating the senses with the gripping incense of myrrh and olibanum. Reverberating with the tobacco-like pull of roasted barley, the heart of Vanille Fatale is a perfect storm of roasted coffee absolute, narcissus and frangipani that seduces with grounded floralcy. Madagascan vanilla blends with rich mahogany, its smoky glamour made all the more exotic with primal suede at the finish.',
      name: 'Vanille Fatale Tom Ford for women and men',
      Link: 'https://www.fragrantica.com/perfume/Tom-Ford/Vanille-Fatale-48029.html',
      For: 'UNISEX'},
    ],
    sex: 'Male',
    type: "['Green (Smells of freshly mowed lawns and crushed green leaves)']",
  },{
    Catogery: 'Green',
    scents: [
      {image: 'assets/images/Green/GREENWOMEN-1.jpg', description: 'The fragrance is a blend of refreshing notes of crushed mint leaves and lemon Limone Primo Fiore Femminello from Calabria. Structure of the composition pushes the limits from fresh citruses to a floral heart which encompasses aquatic jasmine, dewy peony and pink pepper, while a base closes with cedar, yellow sugar and labdanum',
      name: 'Acqua de Gioia by Giorgio Armani',
      Link: 'https://www.fragrantica.com/perfume/Giorgio-Armani/Acqua-di-Gioia-8442.html',
      For: 'FEMALE'},
      {image: 'assets/images/Green/GREENWOMEN-2.jpg', description: 'Top notes are composed of English lavender, pink pepper, and neroli, taking us to the heart of orris absolute, blackberry leaves, and orange blossom combined with a specially patented molecule of the house of Givaudan named Petalia carrying the scent of peony accords. The base incorporates vetiver, musk, and vibrant wood. ',
      name: 'Burberry Brit Rhythm for Women Burberry for women',
      Link: 'https://www.fragrantica.com/perfume/Burberry/Burberry-Brit-Rhythm-for-Women-22839.html',
      For: 'FEMALE'},
      {image: 'assets/images/Green/GREENWOMEN-3.jpg', description: 'It was designed by the noses of the famous Givaudan house. The opening consists of basil, citrus oil, green accords and peach, followed by carnation, cyclamen, hyacinth, jasmine, rose and lily-of-the-valley in the middle, settling at the base of cedar, civet, musk and oakmoss. The bottle is a very elegant and gracious beauty. It was created by Pierre Dinand',
      name: 'Valentino Valentino for women',
      Link: 'https://www.fragrantica.com/perfume/Valentino/Valentino-2583.html',
      For: 'FEMALE'},
      {image: 'assets/images/Green/GREENWOMEN-4.jpg', description: 'If while you slept the indigenous plants, leaves prickling with fervour, grew to a gargantuan size, then Allegria is the conduit that would wake you. Its vital scent that’s lightly vegetal and slightly smoky, instantly sweeps the senses on a roller-coaster of giant stems, plunging and twisting across an Edenic landscape. Fuelled by lush greenery, this ecstatic aroma transforms all that was once black and white into vivid colour.',
      name: 'Allegria Rouge Bunny Rouge for women',
      Link: 'https://www.fragrantica.com/perfume/Rouge-Bunny-Rouge/Allegria-24675.html',
      For: 'FEMALE'},
      {image: 'assets/images/Green/GREENUNISEX-1.jpg', description: 'The nose behind this fragrance is Jean-Claude Ellena. Top notes are coriander, orange blossom, mandarin orange, bergamot, cardamom and lemon; middle notes are jasmine, lily-of-the-valley and bulgarian rose; base notes are sandalwood, amber, musk, green tea, precious woods and cedar.',
      name: 'Eau Parfumee au The Vert Bvlgari for women and men',
      Link: 'https://www.fragrantica.com/perfume/Bvlgari/Eau-Parfumee-au-The-Vert-144.html',
      For: 'UNISEX'},
      {image: 'assets/images/Green/GREENUNISEX-2.jpg', description: 'The stirring spice of saffron and coriander opens the scent, infiltrating the senses with the gripping incense of myrrh and olibanum. Reverberating with the tobacco-like pull of roasted barley, the heart of Vanille Fatale is a perfect storm of roasted coffee absolute, narcissus and frangipani that seduces with grounded floralcy. Madagascan vanilla blends with rich mahogany, its smoky glamour made all the more exotic with primal suede at the finish.',
      name: 'Vanille Fatale Tom Ford for women and men',
      Link: 'https://www.fragrantica.com/perfume/Tom-Ford/Vanille-Fatale-48029.html',
      For: 'UNISEX'},
    ],
    sex: 'Female',
    type: "['Green (Smells of freshly mowed lawns and crushed green leaves)']",
  },{
    Catogery: 'Oceanic',
    scents: [
      {image: 'assets/images/Oceanic/OCEANICMEN-1.jpg', description: 'Ice by Van Gils is a Aromatic Spicy fragrance for men. This is a new fragrance. Ice was launched in 2018. Top notes are sea notes and mint; middle notes are juniper, ginger and ammophila (beach grass); base notes are patchouli, musk and ambergris.',
      name: 'Ice Van Gils for men',
      Link: 'https://www.fragrantica.com/perfume/Van-Gils/Ice-51034.html',
      For: 'MEN'},
      {image: 'assets/images/Oceanic/OCEANICMEN-2.jpg', description: 'Examining it closer once applied you will notice a lingering quality of softer fragranced citrus, fruity and dry hints that hide an essence of pure, refreshing and natural feelings.Based on the combination of notes Zara Deep Blue Sea is classified as Ocean fragrance to the nose. The emanation of flavors and scent notes for Deep Blue Sea unfurl in a whiff of citrus opening top notes including bergamot. The marine heart center notes blend in with sea water while the deep woody base notes leave an impression of cedar.',
      name: 'Deep Blue Sea cologne for Men by Zara',
      Link: 'https://www.perfumemaster.com/zara/deep-blue-sea-mens-cologne',
      For: 'MEN'},
      {image: 'assets/images/Oceanic/OCEANICMEN-3.jpg', description: 'Based on the combination of notes Dolce & Gabbana 4 L"Empereur is classified as Woody Aquatic fragrance to the nose. The emanation of flavors and scent notes for 4 L"Empereur unfurl in a whiff of citrus and floral opening top notes including bergamot, lemon and iris. The aquatic and woody heart center notes blend in with water and cedar while the deep green and musk base notes leave an impression of musk, tobacco and sandalwood.',
      name: '4 L"Empereur cologne for Men by Dolce & Gabbana',
      Link: 'https://www.perfumemaster.com/dolce-gabbana/4-lempereur-mens-cologne',
      For: 'MEN'},
      {image: 'assets/images/Oceanic/OCEANICMEN-4.jpg', description: 'Based on the combination of notes Aramis Aramis Always is classified as Woody Aquatic fragrance to the nose. The fragrance composition is a creation of Ilias Ermenidis, Jean Claude Delville. The emanation of flavors and scent notes for Aramis Always unfurl in a whiff of citrus and spice opening top notes including lime, mandarin orange, cucumber, cinnamon and ginger. The green and herbal heart center notes blend in with marigold, mint and cardamom while the deep woody and amber base notes leave an impression of amber, cedar and vetiver.',
      name: 'Aramis Always cologne for Men by Aramis',
      Link: 'https://www.perfumemaster.com/aramis/aramis-always-mens-cologne',
      For: 'MEN'},
      {image: 'assets/images/Oceanic/OCEANICUNISEX-1.jpg', description: 'The beachy aquatic scent of sand, saltwater, wind, seashells, wind blown sea oats, soft ambergris, and a distant storm fast approaching. It is a crisp, clean, fresh, salty and refreshing aquatic fragrance. Imagine standing on a dock as a storm is about to roll in, the air is thick with energy and as the sky turns gray, you are splashed with salty spray from the gulf. It opens with a briny saltwater and touch of roasted sea shells, similar to Sea of Gray but not quite as heavy on the seaweed. The atmosphere begins with a sunny day at the beach, though a solid slate-gray sky is not far off.',
      name: 'Gulf Breeze Solstice Scents for women and men',
      Link: 'https://www.fragrantica.com/perfume/Solstice-Scents/Gulf-Breeze-52757.html',
      For: 'UNISEX'},
      {image: 'assets/images/Oceanic/OCEANICUNISEX-2.jpg', description: 'Based on the combination of notes Thierry Mugler Mugler Cologne Heal Your Mind is classified as Ocean fragrance to the nose. The emanation of flavors and scent notes for Mugler Cologne Heal Your Mind unfurl in a whiff of aromatic opening top notes including lavender. The marine heart center notes blend in with sea water while the deep animal wildlife base notes leave an impression of ambergris.',
      name: 'Mugler Cologne Heal Your Mind Unisex fragrance by Thierry Mugler',
      Link: 'https://www.perfumemaster.com/thierry-mugler/mugler-cologne-heal-your-mind-unisex-fragrance',
      For: 'UNISEX'},
    ],
    sex: 'Male',
    type: "['Oceanic (Aquatic scents that smell of sea spray or rain mixed with oceanic notes)']",
  },{
    Catogery: 'Oceanic',
    scents: [
      {image: 'assets/images/Oceanic/OCEANICWOMEN-1.jfif', description: 'Based on the combination of notes Giorgio Beverly Hills Ocean Dream is classified as Ocean fragrance to the nose. The fragrance composition is a creation of Alberto Morillas. The emanation of flavors and scent notes for Ocean Dream unfurl in a whiff of white flowers opening top notes including orange blossom. The floral heart center notes blend in with heliotrope and water lily while the deep musk and woody base notes leave an impression of musk and sandalwood.',
      name: 'Ocean Dream perfume for Women by Giorgio Beverly Hills',
      Link: 'https://www.perfumemaster.com/giorgio-beverly-hills/ocean-dream-womens-perfume',
      For: 'FEMALE'},
      {image: 'assets/images/Oceanic/OCEANICWOMEN-2.jfif', description: 'Based on the combination of notes Adolfo Dominguez Private Collection Ambar is classified as Woody Aquatic fragrance to the nose. The fragrance composition is a creation of Ramon Monegal. The emanation of flavors and scent notes for Private Collection Ambar unfurl in a whiff of citrus and marine opening top notes including aldehyde, bergamot and sea water. The floral and fruity heart center notes blend in with tropical fruit while the deep woody and amber base notes leave an impression of amber, cedar and patchouli. ',
      name: 'Private Collection Ambar perfume for Women by Adolfo Dominguez',
      Link: 'https://www.perfumemaster.com/adolfo-dominguez/private-collection-ambar-womens-perfume',
      For: ''},
      {image: 'assets/images/Oceanic/OCEANICWOMEN-3.jfif', description: 'Based on the combination of notes Natura Ekos Agua de Banho Misteriosa Pataqueira is classified as Aquatic Aromatic fragrance to the nose. The fragrance composition is a creation of Veronica Kato. The emanation of flavors and scent notes for Ekos Agua de Banho Misteriosa Pataqueira unfurl in a whiff of marine opening top notes including sea water. The floral heart center notes blend in with floral while the deep green base notes leave an impression of green. ',
      name: 'Ekos Agua de Banho Misteriosa Pataqueira perfume for Women by Natura',
      Link: 'https://www.perfumemaster.com/natura/ekos-agua-de-banho-misteriosa-pataqueira-womens-perfume',
      For: ''},
      {image: 'assets/images/Oceanic/OCEANICWOMEN-4.jfif', description: 'Based on the combination of notes Women Secret Eau My Delice is classified as Aromatic Aquatic fragrance to the nose. The emanation of flavors and scent notes for Eau My Delice unfurl in a whiff of citrus and fruity opening top notes including grapefruit and pomegranate. The floral and fruity heart center notes blend in with orchid and watermelon while the deep musk and woody base notes leave an impression of woody.',
      name: 'Eau My Delice perfume for Women by Women Secret',
      Link: 'https://www.perfumemaster.com/womensecret/eau-my-delice-womens-perfume',
      For: ''},
      {image: 'assets/images/Oceanic/OCEANICUNISEX-1.jpg', description: 'The beachy aquatic scent of sand, saltwater, wind, seashells, wind blown sea oats, soft ambergris, and a distant storm fast approaching. It is a crisp, clean, fresh, salty and refreshing aquatic fragrance. Imagine standing on a dock as a storm is about to roll in, the air is thick with energy and as the sky turns gray, you are splashed with salty spray from the gulf. It opens with a briny saltwater and touch of roasted sea shells, similar to Sea of Gray but not quite as heavy on the seaweed. The atmosphere begins with a sunny day at the beach, though a solid slate-gray sky is not far off.',
      name: 'Gulf Breeze Solstice Scents for women and men',
      Link: 'https://www.fragrantica.com/perfume/Solstice-Scents/Gulf-Breeze-52757.html',
      For: 'UNISEX'},
      {image: 'assets/images/Oceanic/OCEANICUNISEX-2.jpg', description: 'Based on the combination of notes Thierry Mugler Mugler Cologne Heal Your Mind is classified as Ocean fragrance to the nose. The emanation of flavors and scent notes for Mugler Cologne Heal Your Mind unfurl in a whiff of aromatic opening top notes including lavender. The marine heart center notes blend in with sea water while the deep animal wildlife base notes leave an impression of ambergris.',
      name: 'Mugler Cologne Heal Your Mind Unisex fragrance by Thierry Mugler',
      Link: 'https://www.perfumemaster.com/thierry-mugler/mugler-cologne-heal-your-mind-unisex-fragrance',
      For: 'UNISEX'},
    ],
    sex: 'Female',
    type: "['Oceanic (Aquatic scents that smell of sea spray or rain mixed with oceanic notes)']",
  },{
    Catogery: 'Oriental',
    scents: [
      {image: 'assets/images/Oriental/ORIENTALMEN-1.jpg', description: 'A reassuring fragrance with an extremely modern wake. Lavender, a reference to the familiar and comforting smell of beard soap, is enhanced by the sensuality of vanilla.',
      name: 'Le Male by Jean-Paul Gaultier',
      Link: 'https://www.nocibe.fr/jean-paul-gaultier-jean-paul-gaultier-le-male-eau-de-toilette-vaporisateur-40-ml-s152794',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALMEN-2.jpg', description: 'A fresh citrus explosion at the top notes (tangerine, grapefruit, lime and bergamot) is harmonized with a floral sharpness of lavender, nut, spiced notes of coriander and warm cinnamon. Carnation (along with jasmine, rose tree and pine) is restrained with warm patchouli, sandalwood, vetiver, benzoin, vanilla and amber. Subtle aroma of red berries enforces the structure, adding sensuousness and characteristic to the perfume.',
      name: 'Obsession for Men Calvin Klein for men',
      Link: 'https://www.fragrantica.com/perfume/Calvin-Klein/Obsession-for-Men-249.html',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALMEN-3.jpg', description: 'Armani Code by Giorgio Armani is a Oriental Spicy fragrance for men.The nose behind this fragrance is Antoine Lie. Top notes are bergamot and lemon; middle notes are star anise, olive blossom and guaiac wood; base notes are leather, tobacco and tonka bean. This perfume is the winner of award FiFi Award Fragrance Of The Year Men`s Luxe 2006',
      name: 'Armani Code by Giorgio Armani',
      Link: 'https://www.fragrantica.com/perfume/Giorgio-Armani/Armani-Code-412.html',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALMEN-4.jpg', description: 'Bijan With a Twist for Men by Bijan is a Oriental Woody fragrance for men. Bijan With a Twist for Men was launched in 2001. The nose behind this fragrance is Givaudan. The fragrance features coriander, amber, lavender, musk, vanilla and bergamot.',
      name: 'Bijan With a Twist for Men Bijan for men',
      Link: 'https://www.fragrantica.com/perfume/Bijan/Bijan-With-a-Twist-for-Men-3567.html',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALUNISEX-1.jpg', description: 'Ambre Sultan by Serge Lutens is a fragrance for women and men. Ambre Sultan was launched in 2000. The nose behind this fragrance is Christopher Sheldrake. The fragrance features coriander, sandalwood, bay leaf, patchouli, angelica, resins, myrrh, amber, oregano, myrtle, benzoin and vanilla.',
      name: 'Ambre Sultan by Serge Lutens',
      Link: 'https://www.fragrantica.com/perfume/Serge-Lutens/Ambre-Sultan-2760.html',
      For: 'UNISEX'},
      {image: 'assets/images/Oriental/ORIENTALUNISEX-2.jpg', description: 'Bazaar by Abdes Salaam Attars Perfumes is a Oriental fragrance for women and men. The fragrance features spicy notes, resins, cloves, cinnamon, cardamom, incense, orange, patchouli, rose and labdanum.',
      name: 'Bazaar Abdes Salaam Attars Perfumes for women and men',
      Link: 'https://www.fragrantica.com/perfume/Abdes-Salaam-Attars-Perfumes/Bazaar-19571.html',
      For: 'UNISEX'},
    ],
    sex: 'Male',
    type: "['Oriental (Sweet, warm notes like cinnamon, vanilla and musk)']",
  },{
    Catogery: 'Oriental',
    scents: [
      {image: 'assets/images/Oriental/ORIENTALWOMEN-1.jpg', description: 'A unique and addictive fragrance with notes of Bergamot, Praline and Patchouli. Like a precious jewel, give eternal life to your star thanks to the Refill Bottles or in your perfume at the MUGLER Fountain. Olfactory family: Oriental Gourmand.This fragrance of unreason, real manifesto olfactory, is built around three facets: - Celestial facet: Bergamot - Delight facet: Praline - Voluptuous facet: Patchouli.',
      name: 'Angel by Thierry Mugler',
      Link: 'https://www.sephora.fr/p/angel---eau-de-parfum-P22409.html#product-info',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALWOMEN-2.jpg', description: 'The composition opens with the floral notes of rose, peony, jasmine and lily-of-the-valley. The new and modern note of eucaliptus in the middle is refreshing the classic floral buquet. The heart blends with eucaliptus, pear blossom, orchid and syringa. Oriental base includes sandal and Tonka bean. ',
      name: 'Contradiction by Calvin Klein',
      Link: 'https://www.fragrantica.com/perfume/Calvin-Klein/Contradiction-255.html',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALWOMEN-3.jpg', description: 'Al Lolo Al-Maknoon by Abdul Samad Al Qurashi is a Oriental fragrance for women. Top notes are litchi and mandarin orange; middle notes are taif rose and musk; base notes are cedar, sandalwood and agarwood (oud).',
      name: 'Al Lolo Al-Maknoon Abdul Samad Al Qurashi for women',
      Link: 'https://www.fragrantica.com/perfume/Abdul-Samad-Al-Qurashi/Al-Lolo-Al-Maknoon-21297.html',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALWOMEN-4.jpg', description: 'Delicious by Sara La Fountain by Acorelle is a Oriental Vanilla fragrance for women. Top notes are rose and honey; middle notes are tonka bean and almond; base notes are vanilla and praline.',
      name: 'Delicious by Sara La Fountain Acorelle for women',
      Link: 'https://www.fragrantica.com/perfume/Acorelle/Delicious-by-Sara-La-Fountain-35475.html',
      For: ''},
      {image: 'assets/images/Oriental/ORIENTALUNISEX-1.jpg', description: 'Ambre Sultan by Serge Lutens is a fragrance for women and men. Ambre Sultan was launched in 2000. The nose behind this fragrance is Christopher Sheldrake. The fragrance features coriander, sandalwood, bay leaf, patchouli, angelica, resins, myrrh, amber, oregano, myrtle, benzoin and vanilla.',
      name: 'Ambre Sultan by Serge Lutens',
      Link: 'https://www.fragrantica.com/perfume/Serge-Lutens/Ambre-Sultan-2760.html',
      For: 'UNISEX'},
      {image: 'assets/images/Oriental/ORIENTALUNISEX-2.jpg', description: 'Bazaar by Abdes Salaam Attars Perfumes is a Oriental fragrance for women and men. The fragrance features spicy notes, resins, cloves, cinnamon, cardamom, incense, orange, patchouli, rose and labdanum.',
      name: 'Bazaar Abdes Salaam Attars Perfumes for women and men',
      Link: 'https://www.fragrantica.com/perfume/Abdes-Salaam-Attars-Perfumes/Bazaar-19571.html',
      For: 'UNISEX'},
    ],
    sex: 'Female',
    type: "['Oriental (Sweet, warm notes like cinnamon, vanilla and musk)']",
  },{
    Catogery: 'Spicy',
    scents: [
      {image: 'assets/images/Spicy/SPICYMEN-1.jpg', description: 'Romance for Men by Ralph Lauren is a Woody Aromatic fragrance for men. Romance for Men was launched in 1999. The nose behind this fragrance is Antoine Lie. Top notes are orange, ginseng, ginger, black currant, pistachio leaf, lavender and mandarin orange; middle notes are lily, celery, basil, saffron, rose, geranium and cardamom; base notes are pine tree, patchouli, musk, oakmoss and vetiver. ',
      name: 'Romance for Men by Ralph Lauren',
      Link: 'https://www.fragrantica.com/perfume/Ralph-Lauren/Romance-for-Men-2556.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYMEN-2.jpg', description: 'Young English actor Hugh Dancy sitting in front of a fabulous old-timer embodies to perfection the laid-back, elegant spirit and philosophy of this new scent for men; demureness and irony, a classic turned into casual fragrance. Citrusy freshness of mandarin and bergamot and cool, spicy notes of ginger and cardamom preceed a masculine heart of cedar and nutmeg with a touch of refined wild rose. The base is sensual due to precious egzotic woods, gray amber, Tonka bean and patchouli.',
      name: 'Burberry Brit for Men by Burberr',
      Link: 'https://www.fragrantica.com/perfume/Burberry/Burberry-Brit-for-Men-1115.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYMEN-3.jpg', description: 'Spicebomb comes out in January 2012 as an explosive and extrovert oriental - woody and spicy composition. Perfumer Olivier Polge blended spices with sensual undertones; creating two diametrically opposed fragrant accords: 1. the addictive and fiery one and 2. the explosive and icy one. The fiery accord contains notes of chili, saffron, leather, tobacco and vetiver. The explosive one includes bergamot, grapefruit, elemi and pink pepper.',
      name: 'Spicebomb Viktor&Rolf for men',
      Link: 'https://www.fragrantica.com/perfume/Viktor-Rolf/Spicebomb-13857.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYMEN-4.jpg', description: 'Boss Selection begins with lively and fresh green notes, juicy grapefruit and mandarin, along with spicy pink peppercorn nuance. In the heart of the fragrance is the aroma of geranium and cedar leaves, surrounded by star anise and petitgrain. The woody drydown is made of patchouli, vetiver, cedarwood, heliotrope and transparent musky notes, all together accentuating the masculine character of this fragrance.',
      name: 'Boss Selection Hugo Boss for men',
      Link: 'https://www.fragrantica.com/perfume/Hugo-Boss/Boss-Selection-387.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYUNISEX-1.jpg', description: 'Frankincense and Myrrh traditionally smell spiritual and religious but in Russian Gold, they have been reconstructed to feel contemporary yet sophisticated. Top notes open the composition with Pink Pepper, Saffron, Mace, Cardamom, Nutmeg, Cumin & Myrtle. The heart develops Frankincense, Geranium & Myrrh. Depth and warmth in the base are provided by patchouli Oud, Leather, musk along with Cedar, Sandal wood',
      name: 'Russian Gold Pure Gold Perfumes for women and men',
      Link: 'https://www.fragrantica.com/perfume/Pure-Gold-Perfumes/Russian-Gold-41373.html',
      For: 'UNISEX'},
      {image: 'assets/images/Spicy/SPICYUNISEX-2.jpg', description: '8 88 by Comme des Garcons is a Oriental Spicy fragrance for women and men. 8 88 was launched in 2008. The nose behind this fragrance is Antoine Lie. Top notes are coriander, turmeric and papyrus; middle notes are incense, saffron and geranium; base notes are amber and patchouli.',
      name: '8 88 Comme des Garcons for women and men',
      Link: 'https://www.fragrantica.com/perfume/Comme-des-Garcons/8-88-2140.html',
      For: 'UNISEX'},
    ],
    sex: 'Male',
    type: "['Spicy (raw fresh aroma of cardamom, sage or saffron)']",
  },{
    Catogery: 'Spicy',
    scents: [
      {image: 'assets/images/Spicy/SPICYWOMEN-1.jpg', description: 'Leva by O Driu is a Oriental Floral fragrance for women. The nose behind this fragrance is Angelo Orazio Pregoni. Top notes are grapefruit, black pepper, jasmine and tagetes; middle notes are turmeric, vanilla, nard himalayan (jatamansi), basil and lavender; base notes are lemongrass, soybean, woody notes and vetiver.',
      name: 'Leva O Driu for women',
      Link: 'https://www.fragrantica.com/perfume/O-Driu/Leva-13351.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYWOMEN-2.jpg', description: 'With the new makeup collection, Tom Ford presents three new fragrances: Jasmine Rouge, Violet Blonde and Santal Blush (Signature Collection) in September 2011. Santal Blush is an enchanting, mysterious, glamorous and exotic woody - spicy scent. It is ruled by creamy notes of sandalwood and spices, with rich floral and woody tones.Top notes: Indian spices, cumin, cinnamon, carrot seeds and fenugreek. Heart: jasmine, ylang-ylang and rose. Base: Australian sandalwood, cedar, benzoin, musk and oud.',
      name: 'Santal Blush Tom Ford for women',
      Link: 'https://www.fragrantica.com/perfume/Tom-Ford/Santal-Blush-12766.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYWOMEN-3.jpg', description: 'Cruda by Morph is a Oriental Floral fragrance for women. Top notes are bergamot, cedar and nigella; middle notes are damask rose, cinnamon and cloves; base notes are amber, patchouli, cashmeran, labdanum, vanilla, musk, tonka bean and ambergris.',
      name: 'Cruda Morph for women',
      Link: 'https://www.fragrantica.com/perfume/Morph/Cruda-28145.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYWOMEN-4.jpg', description: 'Incense Memoir Woman by Fragrenza is a Chypre fragrance for women. Incense Memoir Woman was launched in 2019. Top notes are mandarin orange, cardamom, absinthe and pink pepper; middle notes are pepper, clove, poplar (populus) buds, white flowers, rose, jasmine and dark woodsy notes; base notes are styrax, oakmoss, castoreum, leather, labdanum, fenugreek and musk.',
      name: 'Incense Memoir Woman Fragrenza for women',
      Link: 'https://www.fragrantica.com/perfume/Fragrenza/Incense-Memoir-Woman-60703.html',
      For: ''},
      {image: 'assets/images/Spicy/SPICYUNISEX-1.jpg', description: 'Frankincense and Myrrh traditionally smell spiritual and religious but in Russian Gold, they have been reconstructed to feel contemporary yet sophisticated. Top notes open the composition with Pink Pepper, Saffron, Mace, Cardamom, Nutmeg, Cumin & Myrtle. The heart develops Frankincense, Geranium & Myrrh. Depth and warmth in the base are provided by patchouli Oud, Leather, musk along with Cedar, Sandal wood',
      name: 'Russian Gold Pure Gold Perfumes for women and men',
      Link: 'https://www.fragrantica.com/perfume/Pure-Gold-Perfumes/Russian-Gold-41373.html',
      For: 'UNISEX'},
      {image: 'assets/images/Spicy/SPICYUNISEX-2.jpg', description: '8 88 by Comme des Garcons is a Oriental Spicy fragrance for women and men. 8 88 was launched in 2008. The nose behind this fragrance is Antoine Lie. Top notes are coriander, turmeric and papyrus; middle notes are incense, saffron and geranium; base notes are amber and patchouli.',
      name: '8 88 Comme des Garcons for women and men',
      Link: 'https://www.fragrantica.com/perfume/Comme-des-Garcons/8-88-2140.html',
      For: 'UNISEX'},
    ],
    sex: 'Female',
    type: "['Spicy (raw fresh aroma of cardamom, sage or saffron)']",
  },{
    Catogery: 'Woody',
    scents: [
      {image: 'assets/images/Woody/WOODYMEN-1.jpg', description: 'Calvin Klein is an Aromatic Green fragrance for men. The nose behind this fragrance is Steve Demercado. Top notes are eucalyptus, melon, juniper, grapefruit, mango and bergamot; middle notes are rosemary, cypress, fir, sage, birch and sea notes; base notes are sandalwood, amber, patchouli, oakmoss and vetiver.',
      name: 'Escape For Men by Calvin Klein',
      Link: 'https://www.fragrantica.com/perfume/Calvin-Klein/Escape-for-Men-272.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYMEN-2.jpg', description: 'Aqua Kenzo pour Homme is developed by perfumer duo Ane Ayo and Philippe Romano. Spicy and fresh notes of pink pepper are mixed with hazelnut leaf, sesame and creamy sandalwood accord.Kenzo launches two new fresh, water-inspired fragrances called Aqua Kenzo.',
      name: 'Kenzo pour Homme by Kenzo',
      Link: 'https://www.fragrantica.com/perfume/Kenzo/Aqua-Kenzo-pour-Homme-49290.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYMEN-3.jpg', description: 'Reflets d Eau de Rochas Pour Homme by Rochas is a Woody Aromatic fragrance for men. Reflets d Eau de Rochas Pour Homme was launched in 2006. Top notes are nutmeg, lemon, bergamot, tangerine and cardamom; middle notes are melon, violet and water lily; base notes are sandalwood, amber and musk.',
      name: 'Eau de Rochas pour Homme by Rochas',
      Link: 'https://www.fragrantica.com/perfume/Rochas/Reflets-d-Eau-de-Rochas-Pour-Homme-5151.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYMEN-4.jpg', description: 'Image by Cerruti is a Aromatic Green fragrance for men. The nose behind this fragrance is Ursula Wandel. Top notes are plum, banana leaf, pear and pepper; middle notes are cypress, fig leaf, jasmine and guaiac wood; base notes are sandalwood, amber, patchouli, tahitian vetiver, musk and cedar.',
      name: 'Cerruti Image by Cerruti',
      Link: 'https://www.fragrantica.com/perfume/Cerruti/Image-332.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYUNISEX-1.jpg', description: '"inspired by Paris in the late 1920s and its infatuation with African culture, art, music, and dance.This mix of Parisian avant-garde and African culture shaped a unique and vibrant expression. The intense life, the excess and euphoria is illustrated by Bal d Afriques neroli, African marigold, and Moroccan cedarwood."Top notes include: bergamot, lemon, neroli, African marigold, Bucchu. Middle notes include: violet, jasmine, and cyclamen. The base is composed of black amber, musk, vetiver, and Moroccan cedarwood.',
      name: 'Bal d "Afrique Byredo for women and men',
      Link: 'https://www.fragrantica.com/perfume/Byredo/Bal-d-Afrique-6458.html',
      For: 'UNISEX'},
      {image: 'assets/images/Woody/WOODYUNISEX-2.jpg', description: ':   Philosykos by Diptyque is a Woody Aromatic fragrance for women and men. Philosykos was launched in 1996. The nose behind this fragrance is Olivia Giacobetti. Top notes are fig leaf and fig; middle notes are coconut and green notes; base notes are cedar, woody notes and fig tree.',
      name: 'Philosykos Diptyque for women and men',
      Link: 'https://www.fragrantica.com/perfume/Diptyque/Philosykos-3865.html',
      For: 'UNISEX'},
    ],
    sex: 'Male',
    type: "['Woody [Chypre] (Aromatic scents like cedar-wood, sandalwood, bergamot or vetiver)']",
  },{
    Catogery: 'Woody',
    scents: [
      {image: 'assets/images/Woody/WOODYWOMEN-1.jpg', description: 'This modern and elegant fragrance opens with notes of mandarin, galbanum, orange, and orange blossom which lead to the heart composed of iris, cedar and vetiver. The base is composed of incense and benzoin. The fragrance was designed by Daniela Roche-Andrier of Givaudan. It is captured in an elegant glass bottle reminiscent of retro perfume bottles.',
      name: 'Infusion de Iris by Prada',
      Link: 'https://www.fragrantica.com/perfume/Prada/Infusion-d-Iris-1795.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYWOMEN-2.jpg', description: 'The composition opens with spicy accords of ginger and cinnamon, combined with woodsy elegance of cedar wood. The heart reveals abundance of fruity and feminine floral notes; peach, plum, orange blossom, violets, spices. The base unites cedar, vanilla, sandal wood, benzoin, musk and cinnamon. The fragrance was created by Christopher Sheldrake in cooperation with Pierre Bourdon',
      name: 'Feminite du Bois by Shiseido',
      Link: 'https://www.fragrantica.com/perfume/Shiseido/Feminite-du-Bois-1271.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYWOMEN-3.jpg', description: 'The trace has become more mysterious and rich, thanks to exotic woods – patchouli and sandalwood. Both variances of the fragrance can be described as floral chypre with intensive musk nuance, only the first one is sharper and more aggressive, while the second one is sweeter and softer.',
      name: 'Narciso Rodriguez For Her Narciso Rodriguez for women',
      Link: 'https://www.fragrantica.com/perfume/Narciso-Rodriguez/Narciso-Rodriguez-For-Her-209.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYWOMEN-4.jpg', description: 'This perfume is created by Nejla Barbir and its top note includes bergamot, mandarin, palisander, aldehyde, peony and broom followed by heart note composed of jasmine, rose, ylang-ylang, lily, wallflower, lichen. Base notes are vanilla, patchouli, benzoin, sandalwood, amber, oakmoss, and musk. Its innovative bottle with rounded edges is designed by Veronique Monod. Dune also won a 1993 Fifi award.',
      name: 'Dune Christian Dior for women',
      Link: 'https://www.fragrantica.com/perfume/Christian-Dior/Dune-221.html',
      For: ''},
      {image: 'assets/images/Woody/WOODYUNISEX-1.jpg', description: '"inspired by Paris in the late 1920s and its infatuation with African culture, art, music, and dance.This mix of Parisian avant-garde and African culture shaped a unique and vibrant expression. The intense life, the excess and euphoria is illustrated by Bal d Afriques neroli, African marigold, and Moroccan cedarwood."Top notes include: bergamot, lemon, neroli, African marigold, Bucchu. Middle notes include: violet, jasmine, and cyclamen. The base is composed of black amber, musk, vetiver, and Moroccan cedarwood.',
      name: 'Bal d "Afrique Byredo for women and men',
      Link: 'https://www.fragrantica.com/perfume/Byredo/Bal-d-Afrique-6458.html',
      For: 'UNISEX'},
      {image: 'assets/images/Woody/WOODYUNISEX-2.jpg', description: ':   Philosykos by Diptyque is a Woody Aromatic fragrance for women and men. Philosykos was launched in 1996. The nose behind this fragrance is Olivia Giacobetti. Top notes are fig leaf and fig; middle notes are coconut and green notes; base notes are cedar, woody notes and fig tree.',
      name: 'Philosykos Diptyque for women and men',
      Link: 'https://www.fragrantica.com/perfume/Diptyque/Philosykos-3865.html',
      For: 'UNISEX'},
    ],
    sex: 'Female',
    type: "['Woody [Chypre] (Aromatic scents like cedar-wood, sandalwood, bergamot or vetiver)']",
  }]
}]

@Component({
  selector: 'app-recommendation-panel',
  templateUrl: './recommendation-panel.component.html',
  styleUrls: ['./recommendation-panel.component.css'],
  animations:[
    trigger('fade', [
      transition('void => *', [style({ opacity: 0 }), animate('900ms', style({ opacity: 1 }))]),
      transition('* => void', [style({ opacity: 1 }), animate('900ms', style({ opacity: 0 }))]),
    ])
  ]
})
export class RecommendationPanelComponent implements OnInit {
  categorys = purfumes[0].categories;
  eval = this.categorys[0].scents;
  current = 0;
  category;
  age;
  prediction: any
  getRec: string = "http://ec2-100-26-219-28.compute-1.amazonaws.com:3000/get_recommendation/420";
  constructor(private http:HttpClient,private router:Router, private route: ActivatedRoute) {
    this.route.queryParams.subscribe(params => {
      if (params && params.special) {
        this.prediction = JSON.parse(params.special)
        console.log(this.prediction);
      
        Object.entries(this.prediction).forEach(([key, value]) => {
          console.log();
          this.category = this.categorys.filter(x => x.type === value)[0];
        })
        // this.category = this.categorys.filter(x => x.type === this.prediction)[0];
        // console.log(this.category.type);
        
      }
    });
  
  }

  ngOnInit(): void {
    // // console.log(this.categorys);
    // this.getprediction();
    // setInterval(() => {
    //   this.current = ++this.current % this.eval.length;
    // }, 3000);
  }

  getprediction() {
    this.http.get(this.getRec).subscribe(data => {
      var pred = data;
      
    })
  }
  logout() {
    this.router.navigate((['login']));
  }

}